--DROP TABLE PET.ROLES;
--DROP TABLE PET.USERS;
--DROP TABLE PET.USER_ROLES;
--DROP TABLE PET.PRODUCTS;
--DROP TABLE PET.PRODUCT_CATEGORIES;
--DROP TABLE PET.ORDERS;
--DROP TABLE PET.ORDER_DETAILS;


--DROP SEQUENCE PET.ROLES_SEQUENCE; 
--DROP SEQUENCE PET.USERS_SEQUENCE; 
--DROP SEQUENCE PET.USER_ROLES_SEQUENCE ;
--DROP SEQUENCE PET.PRODUCT_CATEGORIES_SEQUENCE ;
--DROP SEQUENCE PET.PRODUCTS_SEQUENCE ;
--DROP SEQUENCE PET.ORDERS_SEQUENCE ;
--DROP SEQUENCE PET.ORDERS_DETAILS_SEQUENCE;

--DROP SCHEMA PET;

CREATE SCHEMA PET;

CREATE SEQUENCE PET.ROLES_SEQUENCE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE PET.USERS_SEQUENCE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE PET.USER_ROLES_SEQUENCE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE PET.PRODUCT_CATEGORIES_SEQUENCE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE PET.PRODUCTS_SEQUENCE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE PET.ORDERS_SEQUENCE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE PET.ORDERS_DETAILS_SEQUENCE START WITH 1 INCREMENT BY 1;


CREATE TABLE PET.ROLES ( 
	ROLE_ID              integer  DEFAULT (NEXT VALUE FOR PET.ROLES_SEQUENCE) NOT NULL,
	NAME                 varchar(255)   ,
	CONSTRAINT CONSTRAINT_4 PRIMARY KEY ( ROLE_ID )
 );



CREATE TABLE PET.USERS ( 
	USER_ID              integer  DEFAULT (NEXT VALUE FOR PET.USERS_SEQUENCE) NOT NULL,
	ADDRESS              varchar(255)   ,
	CITY                 varchar(255)   ,
	EMAIL                varchar(255)   ,
	FULL_NAME            varchar(255)   ,
	PASSWORD             varchar(255)   ,
	PIN_CODE             varchar(255)   ,
	STATUS               smallint   NOT NULL,
	USERNAME             varchar(255)   ,
	CONSTRAINT CONSTRAINT_4D PRIMARY KEY ( USER_ID )
 );





CREATE TABLE PET.USER_ROLES ( 
	USER_ROLE_ID         integer  DEFAULT (NEXT VALUE FOR PET.USER_ROLES_SEQUENCE) NOT NULL,
	USER_ID              integer   NOT NULL,
	ROLE_ID              integer   NOT NULL,
	CONSTRAINT CONSTRAINT_C PRIMARY KEY ( USER_ROLE_ID )
 );

CREATE INDEX IDX_USER_ROLES ON PET.USER_ROLES ( USER_ID );

CREATE INDEX IDX_USER_ROLES_0 ON PET.USER_ROLES ( ROLE_ID );

ALTER TABLE PET.USER_ROLES ADD CONSTRAINT FK_USER_ROLES FOREIGN KEY ( USER_ID ) REFERENCES PET.USERS( USER_ID ) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PET.USER_ROLES ADD CONSTRAINT FK_USER_ROLES_0 FOREIGN KEY ( ROLE_ID ) REFERENCES PET.ROLES( ROLE_ID ) ON DELETE RESTRICT ON UPDATE RESTRICT;







CREATE TABLE PET.PRODUCT_CATEGORIES ( 
	CATEGORY_ID          integer  DEFAULT (NEXT VALUE FOR PET.PRODUCT_CATEGORIES_SEQUENCE) NOT NULL,
	DESCRIPTION          varchar(255)   ,
	NAME                 varchar(255)   ,
	CONSTRAINT CONSTRAINT_5 PRIMARY KEY ( CATEGORY_ID )
 );




CREATE TABLE PET.PRODUCTS ( 
	PRODUCT_ID           integer  DEFAULT (NEXT VALUE FOR PET.PRODUCTS_SEQUENCE) NOT NULL,
	DESCRIPTION          varchar(255)   ,
	NAME                 varchar(255)   ,
	PRICE                integer   NOT NULL,
	CATEGORY_ID          integer   ,
	CONSTRAINT CONSTRAINT_F PRIMARY KEY ( PRODUCT_ID )
 );

CREATE INDEX FKF2D1C1643544AD24_INDEX_8 ON PET.PRODUCTS ( CATEGORY_ID );

ALTER TABLE PET.PRODUCTS ADD CONSTRAINT FKF2D1C1643544AD24 FOREIGN KEY ( CATEGORY_ID ) REFERENCES PET.PRODUCT_CATEGORIES( CATEGORY_ID ) ON DELETE RESTRICT ON UPDATE RESTRICT;



CREATE TABLE PET.ORDERS ( 
	ORDER_ID             integer  DEFAULT (NEXT VALUE FOR PET.ORDERS_SEQUENCE) NOT NULL,
	AMOUNT               integer   NOT NULL,
	SHIP_ADDRESS         varchar(255)   ,
	STATUS               smallint   NOT NULL,
	USER_ID              integer   ,
	ORDER_DATE           date   NOT NULL,
	CANCEL_DATE          date   ,
	CONSTRAINT CONSTRAINT_8 PRIMARY KEY ( ORDER_ID )
 );

CREATE INDEX FK8B7256E5F8AAAA9F_INDEX_7 ON PET.ORDERS ( USER_ID );

ALTER TABLE PET.ORDERS ADD CONSTRAINT FK8B7256E5F8AAAA9F FOREIGN KEY ( USER_ID ) REFERENCES PET.USERS( USER_ID ) ON DELETE RESTRICT ON UPDATE RESTRICT;


CREATE TABLE PET.ORDER_DETAILS ( 
	ODETAILS_ID          integer  DEFAULT (NEXT VALUE FOR PET.ORDERS_DETAILS_SEQUENCE) NOT NULL,
	PRODUCT_ID           integer   NOT NULL,
	QUANTITY             integer   NOT NULL,
	COST                 integer   NOT NULL,
	ORDER_ID             integer   NOT NULL,
	CONSTRAINT CONSTRAINT_80 PRIMARY KEY ( ODETAILS_ID )
 );

CREATE INDEX IDX_ORDER_DETAILS ON PET.ORDER_DETAILS ( ORDER_ID );

CREATE INDEX IDX_ORDER_DETAILS_0 ON PET.ORDER_DETAILS ( PRODUCT_ID );

ALTER TABLE PET.ORDER_DETAILS ADD CONSTRAINT FK_ORDER_DETAILS FOREIGN KEY ( ORDER_ID ) REFERENCES PET.ORDERS( ORDER_ID ) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PET.ORDER_DETAILS ADD CONSTRAINT FK_ORDER_DETAILS_0 FOREIGN KEY ( PRODUCT_ID ) REFERENCES PET.PRODUCTS( PRODUCT_ID ) ON DELETE RESTRICT ON UPDATE RESTRICT;


